#ifndef DRAW_TOOL_H
#define DRAW_TOOL_H

typedef enum							e_alignment_mode
{
	PRIVATE_ALIGNMENT_HORIZONTAL_LEFT	= (1 << 0),
	PRIVATE_ALIGNMENT_HORIZONTAL_CENTER = (1 << 1),
	PRIVATE_ALIGNMENT_HORIZONTAL_RIGHT	= (1 << 2),
	PRIVATE_ALIGNMENT_VERTICAL_TOP		= (1 << 3),
	PRIVATE_ALIGNMENT_VERTICAL_CENTER	= (1 << 4),
	PRIVATE_ALIGNMENT_VERTICAL_BOTTOM	= (1 << 5),

	ALIGNEMENT_LEFT_TOP					= PRIVATE_ALIGNMENT_HORIZONTAL_LEFT | PRIVATE_ALIGNMENT_VERTICAL_TOP,
	ALIGNEMENT_CENTER_TOP				= PRIVATE_ALIGNMENT_HORIZONTAL_CENTER | PRIVATE_ALIGNMENT_VERTICAL_TOP,
	ALIGNEMENT_RIGHT_TOP				= PRIVATE_ALIGNMENT_HORIZONTAL_RIGHT | PRIVATE_ALIGNMENT_VERTICAL_TOP,
	ALIGNEMENT_LEFT_CENTER				= PRIVATE_ALIGNMENT_HORIZONTAL_LEFT | PRIVATE_ALIGNMENT_VERTICAL_CENTER,
	ALIGNEMENT_CENTER					= PRIVATE_ALIGNMENT_HORIZONTAL_CENTER | PRIVATE_ALIGNMENT_VERTICAL_CENTER,
	ALIGNEMENT_RIGHT_CENTER				= PRIVATE_ALIGNMENT_HORIZONTAL_RIGHT | PRIVATE_ALIGNMENT_VERTICAL_CENTER,
	ALIGNEMENT_LEFT_BOTTOM				= PRIVATE_ALIGNMENT_HORIZONTAL_LEFT | PRIVATE_ALIGNMENT_VERTICAL_BOTTOM,
	ALIGNEMENT_CENTER_BOTTOM			= PRIVATE_ALIGNMENT_HORIZONTAL_CENTER | PRIVATE_ALIGNMENT_VERTICAL_BOTTOM,
	ALIGNEMENT_RIGHT_BOTTOM				= PRIVATE_ALIGNMENT_HORIZONTAL_RIGHT | PRIVATE_ALIGNMENT_VERTICAL_BOTTOM,
}										t_alignment_mode;

#endif
